#Question 1

In [16]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)
input_values = np.array([0.3, 0.8])
output_values = np.array([0.05, 0.6])

input_bias = 1
hidden_bias = 1

weights_input_hidden = np.array([[0.1, 0.3],
                                 [0.25, 0.8]])

weights_hidden_output = np.array([[0.2, 0.6],
                                  [0.4, 0.7]])
def forward_propagation(inputs, weights, bias):
    weighted_sum = np.dot(inputs, weights) + bias
    activated_output = sigmoid(weighted_sum)
    return activated_output

def backward_propagation(inputs, weights, error, learning_rate):
    gradient = error * sigmoid_derivative(inputs)
    weights += learning_rate * np.dot(inputs.T, gradient)
    return weights

def train_neural_network(inputs, target_outputs, weights_input_hidden, weights_hidden_output, learning_rate, epochs):
    for epoch in range(epochs):
        hidden_layer_input = forward_propagation(inputs, weights_input_hidden, input_bias)
        hidden_layer_output = forward_propagation(hidden_layer_input, weights_hidden_output, hidden_bias)

        output_error = target_outputs - hidden_layer_output

        weights_hidden_output = backward_propagation(hidden_layer_output, weights_hidden_output, output_error, learning_rate)

        hidden_layer_error = output_error.dot(weights_hidden_output.T)
        weights_input_hidden = backward_propagation(hidden_layer_input, weights_input_hidden, hidden_layer_error, learning_rate)

    return hidden_layer_output

learning_rates = [0.5, 0.1, 0.01]
epochs = 1000

for lr in learning_rates:
    trained_output = train_neural_network(input_values, output_values, weights_input_hidden.copy(), weights_hidden_output.copy(), lr, epochs)
    print(f"Output for learning rate {lr}: {trained_output}")


Output for learning rate 0.5: [0.30031301 0.46254176]
Output for learning rate 0.1: [0.30045004 0.45854298]
Output for learning rate 0.01: [0.46405759 0.60910762]


#Question 2


In [10]:
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error

X = [[0.3, 0.8]]
y = [[0.05, 0.6]]
learning_rates = [0.5, 0.1, 0.01]

for lr in learning_rates:
    model = MLPRegressor(hidden_layer_sizes=(2,), activation='logistic', solver='sgd', learning_rate_init=lr, max_iter=10000)
    model.fit(X, y)

    predicted_output = model.predict(X)

    print("Predicted Output using scikit-learn:")
    print(predicted_output)
    print("\nWeights (input to hidden):")
    print(model.coefs_[0])
    print("\nWeights (hidden to output):")
    print(model.coefs_[1])
    

    mse = mean_squared_error(y, predicted_output)
    print(f"\nMean Squared Error: {mse}")


Predicted Output using scikit-learn:
[[0.04995825 0.59999627]]

Weights (input to hidden):
[[ 0.51807946  0.60718665]
 [-0.3486503  -0.40629359]]

Weights (hidden to output):
[[ 0.0775806   0.51058608]
 [-0.51972602  0.09655711]]

Intercepts (biases):
[array([-0.4867019 , -0.31918069]), array([0.22352152, 0.38294377])]

Mean Squared Error: 8.786432649507512e-10
Predicted Output using scikit-learn:
[[0.0423628  0.62204135]]

Weights (input to hidden):
[[-0.3333736  -0.16434776]
 [ 0.33764627 -0.22018467]]

Weights (hidden to output):
[[ 0.48089116 -0.19003156]
 [-0.55244421 -0.45991941]]

Intercepts (biases):
[array([-0.33538626, -0.10278294]), array([0.05303458, 0.90177731])]

Mean Squared Error: 0.00027207396406977297
Predicted Output using scikit-learn:
[[-0.0336906   0.68126277]]

Weights (input to hidden):
[[-0.63627181  0.6594301 ]
 [ 0.41486508  0.64195924]]

Weights (hidden to output):
[[ 0.4461013  -0.20428701]
 [ 0.02145239  0.68018704]]

Intercepts (biases):
[array([ 0.144595