LOGISTIC REGRESSION

1.(a) Split the Diabetes Prediction dataset into training 80% and
testing 20% sets.

In [14]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np

In [15]:
dataset = pd.read_csv('diabetes_prediction_dataset.csv')

X = dataset.drop('diabetes', axis=1)
y = dataset['diabetes']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Training set shapes - X_train:",X_train.shape, " y_train:", y_train.shape)
print("Testing set shapes - X_test:", X_test.shape, " y_test:", y_test.shape)


Training set shapes - X_train: (80000, 8)  y_train: (80000,)
Testing set shapes - X_test: (20000, 8)  y_test: (20000,)


1.(b) Write a code to implement logistic regression for without using the in-built library.

In [16]:
from sklearn.metrics import confusion_matrix
import numpy as np
import pandas as pd

In [17]:
dataset = pd.read_csv('diabetes_prediction_dataset.csv')

dataset = dataset.drop('smoking_history', axis=1)
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

for i in range(X.shape[0]):
    if (X[i][0] == 'Female'):
        X[i][0] = 1
    else:
        X[i][0] = 0


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

Learning_rate = 0.01
cols = X_train.shape[1]
m_initial = np.zeros(cols)
c_initial = 0

no_of_iterations = 100

In [18]:
def gradient_descent(m_initial, c_initial, Learning_rate, no_of_iterations):
    m = m_initial
    c = c_initial
    for i in range(no_of_iterations):
        for j in range(X_train.shape[0]):
            z = np.sum(X_train[j] * m) + c
            y_pred = 1 / (1 + np.exp(-z))  # Sigmoid function
            D_m = np.sum(X_train[j] * (y_pred - y_train[j]))
            D_c = y_pred - y_train[j]

            m -= (Learning_rate * D_m) / cols
            c -= (Learning_rate * D_c) / cols

    return m, c


optimal_m, optimal_c = gradient_descent(m_initial, c_initial, Learning_rate, no_of_iterations)


def Y_Pred(optimal_m, optimal_c, X_test):
    y_pred = np.array([])
    threshold = 0.5
    for i in range(X_test.shape[0]):
        z = np.sum(X_test[i] * optimal_m) + optimal_c
        a = 1 / (1 + np.exp(-z))  # Sigmoid function
        a = a >= threshold
        y_pred = np.append(y_pred, a)
    return y_pred


y = Y_Pred(optimal_m, optimal_c, X_test)


accuracy = np.mean(y == y_test)
print("Accuracy:", accuracy)

cm = confusion_matrix(y_test, y)
print("Confusion Matrix: \n", cm)

Accuracy: 0.9415
Confusion Matrix: 
 [[18292     0]
 [ 1170   538]]


2. (a) Implement the logistic regression model on Iris dataset by using in-built library. Divide the dataset into training and testing sets in the ratio of 90:10

In [19]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import pandas as pd
from sklearn.metrics import accuracy_score

dataset = pd.read_csv('iris.csv')

X = dataset.drop('species', axis=1)
y = dataset['species']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)


model = LogisticRegression()

model.fit(X_train, y_train)
y_pred = model.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix: \n", cm)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.1f}")


Confusion Matrix: 
 [[6 0 0]
 [0 6 0]
 [0 0 3]]
Accuracy: 1.0
